### ISSUE TITLE
树莓派命令行的二维码显示不全、楼主怎么解决的？

### ISSUE THREAD

**Issue by Vxer-Lee** [yi-yun/raspi-chatrobot#1]
<img width="1440" alt="2018-12-09 11 43 59" src="https://user-images.githubusercontent.com/27657137/49693220-bb94c700-fba7-11e8-8757-4363e16452d0.png">

**Comment by yi-yun** [comment]
GitHub 通知设置被我瞎搞坏了，回复没看到，就当给后面看到的人一些建议吧
解决方法：
- 调整参数
- 调整 shell 大小或者分辨率

**Comment by Vxer-Lee** [comment]
虽然现在不研究了，不过还是谢谢🙏

**Comment by yi-yun** [comment]
客气客气
